var searchData=
[
  ['g_20set_20up_20gpios_20for_20i2c_20communication_0',['G. Set up GPIOs for I2C Communication',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md20',1,'']]],
  ['general_20info_1',['A. General info',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md2',1,'']]],
  ['global_20variables_20available_20to_20other_20source_20code_20files_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_2',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md12',1,'']]],
  ['global_20variables_20available_20to_20the_20main_20code_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_3',['global variables available to the main code the tt globals h tt file must be included into tt main c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['global_20variables_20declaration_20definition_20and_20inclusion_20in_20the_20main_20source_20code_4',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['global_20variables_20should_20be_20declared_20in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_5',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md5',1,'']]],
  ['global_20variables_20you_20declared_20in_20tt_20globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_6',['global variables you declared in tt globals h tt must be also defined assigned default values into a tt globals c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md10',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:']]],
  ['globals_20h_20tt_20file_20following_20these_20steps_3a_7',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md5',1,'']]],
  ['globals_20h_20tt_20file_20must_20be_20included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_8',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md12',1,'']]],
  ['globals_20h_20tt_20file_20must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_9',['globals h tt file must be included into tt main c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_10',['globals h tt must be also defined assigned default values into a tt globals c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md10',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:']]],
  ['gpio_20as_20a_20digital_20input_20or_20as_20digital_20output_11',['A. Set up a GPIO as a Digital Input or as Digital Output',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md14',1,'']]],
  ['gpio_20as_20an_20analog_20input_12',['B. Set up a GPIO as an analog Input',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md15',1,'']]],
  ['gpio_20as_20an_20interrupt_20capable_20digital_20input_13',['D. Set up a GPIO as an Interrupt Capable Digital Input',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md17',1,'']]],
  ['gpio_20as_20an_20pwm_20output_14',['C. Set up a GPIO as an PWM Output',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md16',1,'']]],
  ['gpios_20for_20i2c_20communication_15',['G. Set up GPIOs for I2C Communication',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md20',1,'']]],
  ['gpios_20for_20spi_20communication_16',['F. Set up GPIOs for SPI Communication',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md19',1,'']]],
  ['gpios_20for_20uart_20communication_17',['E. Set up GPIOs for UART Communication',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md18',1,'']]],
  ['guide_18',['guide',['../md_Guides_202_8Pin__Mapping__Setup.html',1,'02. Device Configuration Setup Guide'],['../md_Guides_2Using__the__Debugger.html',1,'STM32CubeIDE Debugging Guide'],['../md_Guides_2Timer__Clock.html',1,'Timer Clock Guide']]]
];
