var searchData=
[
  ['c_20global_20variables_20declaration_20definition_20and_20inclusion_20in_20the_20main_20source_20code_0',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['c_20set_20up_20a_20gpio_20as_20an_20pwm_20output_1',['C. Set up a GPIO as an PWM Output',['../md_Guides_202_8Device__Configuration.html#autotoc_md14',1,'']]],
  ['c_20tt_20file_20following_20these_20steps_3a_2',['c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['calibration_3',['Offset Calibration',['../group__ADXL345__OFFSET__REGS.html',1,'']]],
  ['capable_20digital_20input_4',['D. Set up a GPIO as an Interrupt Capable Digital Input',['../md_Guides_202_8Device__Configuration.html#autotoc_md15',1,'']]],
  ['clock_20guide_5',['03. Timer Clock Guide',['../md_Guides_203_8Timer__Setup.html',1,'']]],
  ['clocks_6',['APBx Peripheral Clocks',['../md_Guides_203_8Timer__Setup.html#autotoc_md20',1,'']]],
  ['code_7',['code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'C. Global Variables - Declaration, definition and inclusion in the main source code'],['../md_Guides_205_8Debugger__Guide.html#autotoc_md28',1,'Step Through Code']]],
  ['code_20blocks_8',['STM Code Blocks',['../index.html',1,'']]],
  ['code_20structure_9',['01. The STM32 Code Structure',['../md_Guides_201_8STM32__Code__Structure.html',1,'']]],
  ['code_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_10',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['command_11',['Example 1 – Full Command',['../md_Guides_209_8Parsing__commands.html#autotoc_md57',1,'']]],
  ['command_20parser_12',['Command Parser',['../group__command__parser.html',1,'']]],
  ['command_5fparser_2eh_13',['command_parser.h',['../command__parser_8h.html',1,'']]],
  ['commands_14',['09. Parsing Commands',['../md_Guides_209_8Parsing__commands.html',1,'']]],
  ['communication_15',['communication',['../md_Guides_202_8Device__Configuration.html#autotoc_md16',1,'E. Set up GPIOs for UART Communication'],['../md_Guides_202_8Device__Configuration.html#autotoc_md17',1,'F. Set up GPIOs for SPI Communication'],['../md_Guides_202_8Device__Configuration.html#autotoc_md18',1,'G. Set up GPIOs for I2C Communication']]],
  ['configuration_16',['configuration',['../md_Guides_208_8Using__a__Rotary__Encoder.html#autotoc_md46',1,'Pin configuration'],['../group__ADXL345__TAP__REGS.html',1,'Tap Detection Configuration']]],
  ['configuration_20setup_20guide_17',['02. Device Configuration Setup Guide',['../md_Guides_202_8Device__Configuration.html',1,'']]],
  ['configure_20i²c_20peripheral_18',['1. Configure I²C Peripheral',['../md_Guides_206_8LCD__with__I2C__Module.html#autotoc_md38',1,'']]],
  ['configure_20it_19',['configure it',['../md_Guides_206_8LCD__with__I2C__Module.html#autotoc_md37',1,'How to Configure It'],['../md_Guides_209_8Parsing__commands.html#autotoc_md52',1,'How to Configure It']]],
  ['control_20and_20status_20',['control and status',['../group__ADXL345__FIFO__REGS.html',1,'FIFO Control and Status'],['../group__ADXL345__INT__REGS.html',1,'Interrupt Control and Status']]],
  ['create_20the_20header_20file_20of_20the_20software_20module_3a_21',['Create the header file of the software module:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md9',1,'']]],
  ['create_20the_20source_20file_20of_20the_20software_20module_3a_22',['Create the source file of the software module:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md10',1,'']]],
  ['creating_20a_20software_20module_20and_20its_20local_20variables_23',['D. Creating a software module and its local variables',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md8',1,'']]],
  ['cs_5fpin_24',['CS_Pin',['../structSPI__Helper__t.html#a5cfa2757595b28a6e06b1e9c962d99b9',1,'SPI_Helper_t']]],
  ['cs_5fport_25',['CS_Port',['../structSPI__Helper__t.html#a91aa4580c0dd324965e10fb12e2b147a',1,'SPI_Helper_t']]]
];
