var searchData=
[
  ['debug_20mode_0',['Exit Debug Mode',['../md_Guides_2Using__the__Debugger.html#autotoc_md32',1,'']]],
  ['debugging_20guide_1',['STM32CubeIDE Debugging Guide',['../md_Guides_2Using__the__Debugger.html',1,'']]],
  ['declaration_20definition_20and_20inclusion_20in_20the_20main_20source_20code_2',['declaration definition and inclusion in the main source code',['../md_Guides_2Arduino__to__STM.html#autotoc_md2',1,'A. Global Variables - Declaration, definition and inclusion in the main source code'],['../md_Guides_2Arduino__to__STM.html#autotoc_md7',1,'B. Functions - Declaration, definition and inclusion in the main source code']]],
  ['declared_20in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_3',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md3',1,'']]],
  ['declared_20in_20tt_20globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_4',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md4',1,'']]],
  ['default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_5',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md4',1,'']]],
  ['defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_6',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md4',1,'']]],
  ['definition_20and_20inclusion_20in_20the_20main_20source_20code_7',['definition and inclusion in the main source code',['../md_Guides_2Arduino__to__STM.html#autotoc_md2',1,'A. Global Variables - Declaration, definition and inclusion in the main source code'],['../md_Guides_2Arduino__to__STM.html#autotoc_md7',1,'B. Functions - Declaration, definition and inclusion in the main source code']]],
  ['digital_20input_20output_8',['Digital Input / Output',['../md_Guides_2Peripheral__Setup.html#autotoc_md10',1,'']]],
  ['dma_20mode_20effectively_9',['Using the ADC in DMA mode effectively',['../md_Guides_2Using__the__ADC__with__DMA.html',1,'']]]
];
