var searchData=
[
  ['b_20set_20up_20a_20gpio_20as_20an_20analog_20input_0',['B. Set up a GPIO as an analog Input',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md15',1,'']]],
  ['b_20the_20stm32_20equivalent_20of_20setup_20and_20loop_20functions_20found_20in_20arduine_20ide_1',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_2',['be also defined assigned default values into a tt globals c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md10',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:']]],
  ['be_20declared_20in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_3',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md5',1,'']]],
  ['be_20included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_4',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md12',1,'']]],
  ['be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_5',['be included into tt main c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['blocks_6',['STM Code Blocks',['../index.html',1,'']]],
  ['breakpoints_7',['Set Breakpoints',['../md_Guides_205_8Debugger__Guide.html#autotoc_md29',1,'']]],
  ['build_20and_20flash_20the_20project_8',['Build and Flash the Project',['../md_Guides_205_8Debugger__Guide.html#autotoc_md28',1,'']]]
];
