var searchData=
[
  ['i_20find_20the_20address_0',['How do I find the address??',['../md_Guides_206_8LCD__with__I2C__Module.html#autotoc_md38',1,'']]],
  ['i2c_20communication_1',['G. Set up GPIOs for I2C Communication',['../md_Guides_202_8Device__Configuration.html#autotoc_md18',1,'']]],
  ['i2c_20lcd_2',['I2C LCD',['../group__i2c__lcd.html',1,'']]],
  ['i2c_20module_20md_3',['06. LCD with I2C Module.md',['../md_Guides_206_8LCD__with__I2C__Module.html',1,'']]],
  ['i2c_5flcd_2eh_4',['i2c_lcd.h',['../i2c__lcd_8h.html',1,'']]],
  ['i2c_5flcd_5fhandletypedef_5',['I2C_LCD_HandleTypeDef',['../structI2C__LCD__HandleTypeDef.html',1,'']]],
  ['ide_6',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['identification_7',['Device Identification',['../group__ADXL345__ID__REG.html',1,'']]],
  ['in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_8',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md5',1,'']]],
  ['in_20arduine_20ide_9',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['in_20dma_20mode_20effectively_10',['04. Using the ADC in DMA mode effectively',['../md_Guides_204_8ADC__with__DMA__Setup.html',1,'']]],
  ['in_20the_20main_20source_20code_11',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['in_20tt_20globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_12',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'']]],
  ['inactivity_20detection_13',['Activity/Inactivity Detection',['../group__ADXL345__ACTIVITY__REGS.html',1,'']]],
  ['included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_14',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['inclusion_20in_20the_20main_20source_20code_15',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['info_16',['A. General info',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md2',1,'']]],
  ['input_17',['input',['../md_Guides_202_8Device__Configuration.html#autotoc_md13',1,'B. Set up a GPIO as an analog Input'],['../md_Guides_202_8Device__Configuration.html#autotoc_md15',1,'D. Set up a GPIO as an Interrupt Capable Digital Input']]],
  ['input_20or_20as_20digital_20output_18',['A. Set up a GPIO as a Digital Input or as Digital Output',['../md_Guides_202_8Device__Configuration.html#autotoc_md12',1,'']]],
  ['inspect_20variables_19',['Inspect Variables',['../md_Guides_205_8Debugger__Guide.html#autotoc_md30',1,'']]],
  ['install_20it_20',['How to Install It',['../md_Guides_209_8Parsing__commands.html#autotoc_md45',1,'']]],
  ['installation_21',['Installation',['../md_Guides_206_8LCD__with__I2C__Module.html#autotoc_md36',1,'']]],
  ['int_20only_22',['Example 2 – Name and Int Only',['../md_Guides_209_8Parsing__commands.html#autotoc_md53',1,'']]],
  ['interface_23',['interface',['../group__serial__interface.html',1,'Serial Interface'],['../group__spi__interface.html',1,'SPI Interface']]],
  ['interrupt_20capable_20digital_20input_24',['D. Set up a GPIO as an Interrupt Capable Digital Input',['../md_Guides_202_8Device__Configuration.html#autotoc_md15',1,'']]],
  ['interrupt_20control_20and_20status_25',['Interrupt Control and Status',['../group__ADXL345__INT__REGS.html',1,'']]],
  ['interrupt_20request_20handlers_26',['Setting up the Interrupt Request Handlers',['../md_Guides_208_8Using__a__Rotary__Encoder.html#autotoc_md42',1,'']]],
  ['into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_27',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'']]],
  ['into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_28',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['invalid_20format_29',['Example 4 – Invalid Format',['../md_Guides_209_8Parsing__commands.html#autotoc_md55',1,'']]],
  ['it_30',['it',['../md_Guides_209_8Parsing__commands.html#autotoc_md47',1,'How to Configure It'],['../md_Guides_209_8Parsing__commands.html#autotoc_md45',1,'How to Install It'],['../md_Guides_209_8Parsing__commands.html#autotoc_md49',1,'How to Use It']]],
  ['its_20local_20variables_31',['D. Creating a software module and its local variables',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md8',1,'']]]
];
