var searchData=
[
  ['main_0',['main',['../main_8c.html#a840291bc02cba5474a4cb46a9b9566fe',1,'main.c']]],
  ['main_20code_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_1',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md5',1,'']]],
  ['main_20source_20code_2',['main source code',['../md_Guides_2Arduino__to__STM.html#autotoc_md2',1,'A. Global Variables - Declaration, definition and inclusion in the main source code'],['../md_Guides_2Arduino__to__STM.html#autotoc_md8',1,'B. Functions - Declaration, definition and inclusion in the main source code']]],
  ['main_2ec_3',['main.c',['../main_8c.html',1,'']]],
  ['main_2eh_4',['main.h',['../main_8h.html',1,'']]],
  ['make_20your_20global_20variables_20available_20to_20other_20source_20code_20files_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_5',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md6',1,'']]],
  ['make_20your_20global_20variables_20available_20to_20the_20main_20code_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_6',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md5',1,'']]],
  ['memory_20and_20registers_7',['Memory and Registers',['../md_Guides_2Using__the__Debugger.html#autotoc_md31',1,'']]],
  ['mode_8',['Exit Debug Mode',['../md_Guides_2Using__the__Debugger.html#autotoc_md33',1,'']]],
  ['mode_20effectively_9',['Using the ADC in DMA mode effectively',['../md_Guides_2Using__the__ADC__with__DMA.html',1,'']]],
  ['must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_10',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md4',1,'']]],
  ['must_20be_20included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_11',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md6',1,'']]],
  ['must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_12',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_2Arduino__to__STM.html#autotoc_md5',1,'']]]
];
