var searchData=
[
  ['i_20find_20the_20address_0',['How do I find the address??',['../md_Guides_206_8LCD__with__I2C__Module.html#autotoc_md38',1,'']]],
  ['i2c_20communication_1',['G. Set up GPIOs for I2C Communication',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md18',1,'']]],
  ['i2c_20lcd_2',['I2C LCD',['../group__i2c__lcd.html',1,'']]],
  ['i2c_5flcd_2eh_3',['i2c_lcd.h',['../i2c__lcd_8h.html',1,'']]],
  ['i2c_5flcd_5fhandletypedef_4',['I2C_LCD_HandleTypeDef',['../structI2C__LCD__HandleTypeDef.html',1,'']]],
  ['ide_5',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['identification_6',['Device Identification',['../group__ADXL345__ID__REG.html',1,'']]],
  ['in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_7',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md5',1,'']]],
  ['in_20arduine_20ide_8',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['in_20dma_20mode_20effectively_9',['Using the ADC in DMA mode effectively',['../md_Guides_204_8ADC__with__DMA__Setup.html',1,'']]],
  ['in_20the_20main_20source_20code_10',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['in_20tt_20globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_11',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'']]],
  ['inactivity_20detection_12',['Activity/Inactivity Detection',['../group__ADXL345__ACTIVITY__REGS.html',1,'']]],
  ['included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_13',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['inclusion_20in_20the_20main_20source_20code_14',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['info_15',['A. General info',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md2',1,'']]],
  ['input_16',['input',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md13',1,'B. Set up a GPIO as an analog Input'],['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md15',1,'D. Set up a GPIO as an Interrupt Capable Digital Input']]],
  ['input_20or_20as_20digital_20output_17',['A. Set up a GPIO as a Digital Input or as Digital Output',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md12',1,'']]],
  ['inspect_20variables_18',['Inspect Variables',['../md_Guides_205_8Debugger__Guide.html#autotoc_md30',1,'']]],
  ['installation_19',['Installation',['../md_Guides_206_8LCD__with__I2C__Module.html#autotoc_md36',1,'']]],
  ['interface_20',['interface',['../group__serial__interface.html',1,'Serial Interface'],['../group__spi__interface.html',1,'SPI Interface']]],
  ['interrupt_20capable_20digital_20input_21',['D. Set up a GPIO as an Interrupt Capable Digital Input',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md15',1,'']]],
  ['interrupt_20control_20and_20status_22',['Interrupt Control and Status',['../group__ADXL345__INT__REGS.html',1,'']]],
  ['interrupt_20request_20handlers_23',['Setting up the Interrupt Request Handlers',['../md_Guides_2Using__a__Rotary__Encoder.html#autotoc_md43',1,'']]],
  ['into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_24',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'']]],
  ['into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_25',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['its_20local_20variables_26',['D. Creating a software module and its local variables',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md8',1,'']]]
];
