var searchData=
[
  ['i²c_20peripheral_0',['1. Configure I²C Peripheral',['../md_Guides_206_8LCD.html#autotoc_md40',1,'']]],
  ['i_20find_20the_20address_1',['How do I find the address??',['../md_Guides_206_8LCD.html#autotoc_md46',1,'']]],
  ['i2c_2',['I2C',['../md_Guides_206_8LCD.html#autotoc_md36',1,'']]],
  ['i2c_20communication_3',['G. Set up GPIOs for I2C Communication',['../md_Guides_202_8Device__Configuration.html#autotoc_md18',1,'']]],
  ['i2c_20lcd_4',['I2C LCD',['../group__i2c__lcd.html',1,'']]],
  ['i2c_5flcd_2eh_5',['i2c_lcd.h',['../i2c__lcd_8h.html',1,'']]],
  ['i2c_5flcd_5fhandletypedef_6',['I2C_LCD_HandleTypeDef',['../structI2C__LCD__HandleTypeDef.html',1,'']]],
  ['ide_7',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['identification_8',['Device Identification',['../group__ADXL345__ID__REG.html',1,'']]],
  ['in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_9',['Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md5',1,'']]],
  ['in_20arduine_20ide_10',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['in_20dma_20mode_20effectively_11',['04. Using the ADC in DMA mode effectively',['../md_Guides_204_8ADC__with__DMA__Setup.html',1,'']]],
  ['in_20the_20main_20source_20code_12',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['in_20tt_20globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_13',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'']]],
  ['inactivity_20detection_14',['Activity/Inactivity Detection',['../group__ADXL345__ACTIVITY__REGS.html',1,'']]],
  ['include_20the_20driver_15',['Include the driver',['../md_Guides_206_8LCD.html#autotoc_md54',1,'']]],
  ['included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_16',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['inclusion_20in_20the_20main_20source_20code_17',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['index_18',['index',['../structCircularBuffer.html#aad9df09f63bf7bc7f37b454de4b777ad',1,'CircularBuffer']]],
  ['info_19',['A. General info',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md2',1,'']]],
  ['initialise_20the_20display_20and_20print_20something_20',['Initialise the display and print something',['../md_Guides_206_8LCD.html#autotoc_md55',1,'']]],
  ['initialize_20the_20lcd_20handle_21',['2. Define and Initialize the LCD Handle',['../md_Guides_206_8LCD.html#autotoc_md41',1,'']]],
  ['input_22',['input',['../md_Guides_202_8Device__Configuration.html#autotoc_md13',1,'B. Set up a GPIO as an analog Input'],['../md_Guides_202_8Device__Configuration.html#autotoc_md15',1,'D. Set up a GPIO as an Interrupt Capable Digital Input']]],
  ['input_20or_20as_20digital_20output_23',['A. Set up a GPIO as a Digital Input or as Digital Output',['../md_Guides_202_8Device__Configuration.html#autotoc_md12',1,'']]],
  ['inspect_20variables_24',['Inspect Variables',['../md_Guides_205_8Debugger__Guide.html#autotoc_md30',1,'']]],
  ['install_20it_25',['install it',['../md_Guides_206_8LCD.html#autotoc_md49',1,'B. How to install it'],['../md_Guides_206_8LCD.html#autotoc_md38',1,'B. How to Install It'],['../md_Guides_210_8Send__Receive__Serial__Data__Module.html#autotoc_md77',1,'How to Install It'],['../md_Guides_209_8Parsing__commands.html#autotoc_md63',1,'How to Install It']]],
  ['installation_26',['Installation',['../md_Guides_211_8Using__the__ADXL345__driver.html#autotoc_md86',1,'']]],
  ['int_20only_27',['Example 2 – Name and Int Only',['../md_Guides_209_8Parsing__commands.html#autotoc_md71',1,'']]],
  ['interface_28',['interface',['../group__serial__interface.html',1,'Serial Interface'],['../group__spi__interface.html',1,'SPI Interface']]],
  ['interrupt_20capable_20digital_20input_29',['D. Set up a GPIO as an Interrupt Capable Digital Input',['../md_Guides_202_8Device__Configuration.html#autotoc_md15',1,'']]],
  ['interrupt_20control_20and_20status_30',['Interrupt Control and Status',['../group__ADXL345__INT__REGS.html',1,'']]],
  ['interrupt_20request_20handlers_31',['Setting up the Interrupt Request Handlers',['../md_Guides_208_8Using__a__Rotary__Encoder.html#autotoc_md60',1,'']]],
  ['into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_32',['The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'']]],
  ['into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_33',['To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'']]],
  ['invalid_20format_34',['Example 4 – Invalid Format',['../md_Guides_209_8Parsing__commands.html#autotoc_md73',1,'']]],
  ['it_35',['it',['../md_Guides_206_8LCD.html#autotoc_md37',1,'A. What you can do with it'],['../md_Guides_206_8LCD.html#autotoc_md48',1,'A. What you can do with it'],['../md_Guides_206_8LCD.html#autotoc_md49',1,'B. How to install it'],['../md_Guides_206_8LCD.html#autotoc_md38',1,'B. How to Install It'],['../md_Guides_206_8LCD.html#autotoc_md39',1,'C. How to Configure It'],['../md_Guides_206_8LCD.html#autotoc_md50',1,'C. How to configure it'],['../md_Guides_206_8LCD.html#autotoc_md43',1,'D. How to Use It'],['../md_Guides_206_8LCD.html#autotoc_md53',1,'D. How to use it'],['../md_Guides_209_8Parsing__commands.html#autotoc_md65',1,'How to Configure It'],['../md_Guides_210_8Send__Receive__Serial__Data__Module.html#autotoc_md79',1,'How to Configure It'],['../md_Guides_209_8Parsing__commands.html#autotoc_md63',1,'How to Install It'],['../md_Guides_210_8Send__Receive__Serial__Data__Module.html#autotoc_md77',1,'How to Install It'],['../md_Guides_209_8Parsing__commands.html#autotoc_md67',1,'How to Use It'],['../md_Guides_210_8Send__Receive__Serial__Data__Module.html#autotoc_md81',1,'How to Use It'],['../md_Guides_210_8Send__Receive__Serial__Data__Module.html#autotoc_md75',1,'What You Can Do With It']]],
  ['its_20local_20variables_36',['D. Creating a software module and its local variables',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md8',1,'']]]
];
