var searchData=
[
  ['c_20global_20variables_20declaration_20definition_20and_20inclusion_20in_20the_20main_20source_20code_0',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['c_20set_20up_20a_20gpio_20as_20an_20pwm_20output_1',['C. Set up a GPIO as an PWM Output',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md16',1,'']]],
  ['c_20tt_20file_20following_20these_20steps_3a_2',['c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md10',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['capable_20digital_20input_3',['D. Set up a GPIO as an Interrupt Capable Digital Input',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md17',1,'']]],
  ['clock_20guide_4',['Timer Clock Guide',['../md_Guides_2Timer__Clock.html',1,'']]],
  ['clocks_5',['APBx Peripheral Clocks',['../md_Guides_2Timer__Clock.html#autotoc_md26',1,'']]],
  ['code_6',['code',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md4',1,'C. Global Variables - Declaration, definition and inclusion in the main source code'],['../md_Guides_2Using__the__Debugger.html#autotoc_md34',1,'Step Through Code']]],
  ['code_20blocks_7',['STM Code Blocks',['../index.html',1,'']]],
  ['code_20files_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_8',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md12',1,'']]],
  ['code_20structure_9',['The STM32 Code Structure',['../md_Guides_201_8STM32__Code__Structure.html',1,'']]],
  ['code_20the_20tt_20globals_20h_20tt_20file_20must_20be_20included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_10',['code the tt globals h tt file must be included into tt main c tt file following these steps:',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['command_5fparser_2eh_11',['command_parser.h',['../command__parser_8h.html',1,'']]],
  ['communication_12',['communication',['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md18',1,'E. Set up GPIOs for UART Communication'],['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md19',1,'F. Set up GPIOs for SPI Communication'],['../md_Guides_202_8Pin__Mapping__Setup.html#autotoc_md20',1,'G. Set up GPIOs for I2C Communication']]],
  ['configuration_20setup_20guide_13',['02. Device Configuration Setup Guide',['../md_Guides_202_8Pin__Mapping__Setup.html',1,'']]],
  ['creating_20software_20module_20and_20its_20local_20variables_14',['D. Creating software module and its local variables',['../md_Guides_201_8STM32__Code__Structure.html#autotoc_md8',1,'']]],
  ['cs_5fpin_15',['CS_Pin',['../structSPI__Helper__t.html#a5cfa2757595b28a6e06b1e9c962d99b9',1,'SPI_Helper_t']]],
  ['cs_5fport_16',['CS_Port',['../structSPI__Helper__t.html#a91aa4580c0dd324965e10fb12e2b147a',1,'SPI_Helper_t']]]
];
