var searchData=
[
  ['i2c_20communication_0',['I2C Communication',['../md_Guides_2Peripheral__Setup.html#autotoc_md20',1,'']]],
  ['ide_1',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['in_20a_20tt_20globals_20h_20tt_20file_20following_20these_20steps_3a_2',['in a tt globals h tt file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md5',1,'Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md9',1,'Global variables should be declared in a &lt;tt&gt;globals.h&lt;/tt&gt; file following these steps:']]],
  ['in_20arduine_20ide_3',['B. The STM32 equivalent of setup() and loop() functions found in Arduine IDE',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md3',1,'']]],
  ['in_20dma_20mode_20effectively_4',['Using the ADC in DMA mode effectively',['../md_Guides_2Using__the__ADC__with__DMA.html',1,'']]],
  ['in_20the_20main_20source_20code_5',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['in_20tt_20globals_20h_20tt_20must_20be_20also_20defined_20assigned_20default_20values_20into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_6',['in tt globals h tt must be also defined assigned default values into a tt globals c tt file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md10',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:']]],
  ['included_20into_20that_20souce_20code_20file_20following_20these_20steps_3a_7',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md12',1,'']]],
  ['included_20into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_8',['included into tt main c tt file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['inclusion_20in_20the_20main_20source_20code_9',['C. Global Variables - Declaration, definition and inclusion in the main source code',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md4',1,'']]],
  ['info_10',['A. General info',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md2',1,'']]],
  ['input_11',['Analog Input',['../md_Guides_2Peripheral__Setup.html#autotoc_md15',1,'']]],
  ['input_20output_12',['Digital Input / Output',['../md_Guides_2Peripheral__Setup.html#autotoc_md14',1,'']]],
  ['inspect_20variables_13',['Inspect Variables',['../md_Guides_2Using__the__Debugger.html#autotoc_md33',1,'']]],
  ['interrupt_14',['Setting a timer interrupt',['../md_Guides_2Peripheral__Setup.html#autotoc_md21',1,'']]],
  ['interrupt_20on_20an_20arbitrary_20pin_15',['Triggering an interrupt on an arbitrary pin',['../md_Guides_2Peripheral__Setup.html#autotoc_md17',1,'']]],
  ['into_20a_20tt_20globals_20c_20tt_20file_20following_20these_20steps_3a_16',['into a tt globals c tt file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md10',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md6',1,'The global variables you declared in &lt;tt&gt;globals.h&lt;/tt&gt; must be also defined (assigned default values) into a &lt;tt&gt;globals.c&lt;/tt&gt; file following these steps:']]],
  ['into_20that_20souce_20code_20file_20following_20these_20steps_3a_17',['To make your global variables available to other source code files, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into that souce code file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md12',1,'']]],
  ['into_20tt_20main_20c_20tt_20file_20following_20these_20steps_3a_18',['into tt main c tt file following these steps:',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md11',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:'],['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md7',1,'To make your global variables available to the main code, the &lt;tt&gt;globals.h&lt;/tt&gt; file must be included into &lt;tt&gt;main.c&lt;/tt&gt; file following these steps:']]],
  ['its_20local_20variables_19',['D. Creating software module and its local variables',['../md_Guides_201_8_01STM32__Code__Structure.html#autotoc_md8',1,'']]]
];
